"""add_tahiyatul_prayers

Revision ID: 8cc3ae57846f
Revises: e58bb2b11f73
Create Date: 2026-02-08 23:24:27.517449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc3ae57846f'
down_revision: Union[str, Sequence[str], None] = 'e58bb2b11f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ramadan_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.Column('is_fasting', sa.Boolean(), nullable=True),
    sa.Column('salah_fajr', sa.Boolean(), nullable=True),
    sa.Column('salah_dhuhr', sa.Boolean(), nullable=True),
    sa.Column('salah_asr', sa.Boolean(), nullable=True),
    sa.Column('salah_maghrib', sa.Boolean(), nullable=True),
    sa.Column('salah_isha', sa.Boolean(), nullable=True),
    sa.Column('taraweeh', sa.Boolean(), nullable=True),
    sa.Column('tahajjud', sa.Boolean(), nullable=True),
    sa.Column('duha', sa.Boolean(), nullable=True),
    sa.Column('tahiyatul_masjid', sa.Boolean(), nullable=True),
    sa.Column('tahiyatul_wudu', sa.Boolean(), nullable=True),
    sa.Column('sunnat_fajr', sa.Boolean(), nullable=True),
    sa.Column('sunnat_dhuhr', sa.Boolean(), nullable=True),
    sa.Column('sunnat_asr', sa.Boolean(), nullable=True),
    sa.Column('sunnat_maghrib', sa.Boolean(), nullable=True),
    sa.Column('sunnat_isha', sa.Boolean(), nullable=True),
    sa.Column('quran_para', sa.Integer(), nullable=True),
    sa.Column('quran_page', sa.Integer(), nullable=True),
    sa.Column('quran_ayat', sa.Integer(), nullable=True),
    sa.Column('quran_progress', sa.String(), nullable=True),
    sa.Column('sokal_er_zikr', sa.Boolean(), nullable=True),
    sa.Column('shondha_er_zikr', sa.Boolean(), nullable=True),
    sa.Column('had_sadaqah', sa.Boolean(), nullable=True),
    sa.Column('daily_task', sa.Boolean(), nullable=True),
    sa.Column('jamaat_salat', sa.Boolean(), nullable=True),
    sa.Column('istighfar_70', sa.Boolean(), nullable=True),
    sa.Column('quran_translation', sa.Boolean(), nullable=True),
    sa.Column('allahur_naam_shikkha', sa.Boolean(), nullable=True),
    sa.Column('diner_ayat_shikkha', sa.Boolean(), nullable=True),
    sa.Column('diner_hadith_shikkha', sa.Boolean(), nullable=True),
    sa.Column('miswak', sa.Boolean(), nullable=True),
    sa.Column('calling_relative', sa.Boolean(), nullable=True),
    sa.Column('learning_new', sa.Boolean(), nullable=True),
    sa.Column('spiritual_energy', sa.Integer(), nullable=True),
    sa.Column('reflection_note', sa.Text(), nullable=True),
    sa.CheckConstraint('spiritual_energy >= 1 AND spiritual_energy <= 10', name='energy_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_number', name='_user_day_uc')
    )
    op.create_index(op.f('ix_ramadan_reports_id'), 'ramadan_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ramadan_reports_id'), table_name='ramadan_reports')
    op.drop_table('ramadan_reports')
    # ### end Alembic commands ###
